# Generated by Django 2.2.6 on 2019-10-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0003_auto_20191014_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='accommodates',
            field=models.CharField(default=0, max_length=100, verbose_name='accommodates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='amentites',
            field=models.TextField(default='no', verbose_name='amentites'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='avaliability_365',
            field=models.CharField(default=0, max_length=100, verbose_name='avaliability_365'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='bathrooms',
            field=models.CharField(default=0, max_length=100, verbose_name='bathrooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='bedrooms',
            field=models.CharField(default=0, max_length=100, verbose_name='bedrooms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='calulated_host_listings_count',
            field=models.CharField(default=0, max_length=100, verbose_name='calulated_host_listings_count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.TextField(default='no', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='host_id',
            field=models.CharField(default='no', max_length=100, verbose_name='host_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='host_name',
            field=models.CharField(default='no', max_length=100, verbose_name='host_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='last_review',
            field=models.CharField(default='no', max_length=100, verbose_name='last_review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='minimum_nights',
            field=models.CharField(default=0, max_length=100, verbose_name='minimum_nights'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='neighbourhood_cleansed',
            field=models.CharField(default='no', max_length=100, verbose_name='neighbourhood_cleansed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='number_of_reviews',
            field=models.CharField(default=0, max_length=100, verbose_name='number_of_reviews'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='reviews_per_month',
            field=models.CharField(default=0, max_length=100, verbose_name='reviews_per_month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='room_type',
            field=models.CharField(default='no', max_length=100, verbose_name='room_type'),
            preserve_default=False,
        ),
    ]
