# Generated by Django 2.2.6 on 2019-10-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0005_auto_20191014_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='amentites',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='calulated_host_listings_count',
        ),
        migrations.AddField(
            model_name='listings',
            name='amenities',
            field=models.TextField(default='no', verbose_name='amenities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listings',
            name='calculated_host_listings_count',
            field=models.CharField(default=0, max_length=100, verbose_name='calculated_host_listings_count'),
            preserve_default=False,
        ),
    ]
