# Generated by Django 2.2.6 on 2019-10-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0006_auto_20191014_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='price_adjust',
            field=models.IntegerField(default=-1, verbose_name='price_adjust'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='accommodates',
            field=models.IntegerField(verbose_name='accommodates'),
        ),
    ]
