# Generated by Django 2.2.6 on 2019-10-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0007_auto_20191014_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='review_scores_rating',
            field=models.IntegerField(verbose_name='review_scores_rating'),
        ),
    ]
