# Generated by Django 2.2.6 on 2019-10-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0008_auto_20191014_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='accommodates',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price_adjust',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='review_scores_rating',
            field=models.IntegerField(),
        ),
    ]
