# Generated by Django 2.2.6 on 2019-10-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houduan', '0009_auto_20191014_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic_reference',
            name='item4',
            field=models.CharField(default=0, max_length=255, verbose_name='item4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic_reference',
            name='item5',
            field=models.CharField(default=0, max_length=255, verbose_name='item5'),
            preserve_default=False,
        ),
    ]
